### PR TITLE
Separating pure string operations from mldig

### PR DESCRIPTION
**Pull request by heidi-ann**
This PR makes the following changes:
- renaming mldig.ml to mldig_unix.ml due to use of Unix
- creates a new mldig.ml and mldig.mli for the pure operations
- adds the string_of_x function to mldig.ml

The purpose of this change is allow mirage application to use digs pretty printing of Dns packets.

### CODE REVIEW

**Comment by dsheets** [comment]
Could we keep the tool named `mldig` but name the module just `Dig`? Otherwise, this looks good.

Also, could you modify the Travis script to stop calling `make dns-depend` since <https://github.com/mirage/mirage-skeleton/commit/93cc9954666c859f6afe552ebcaafc9a70af1ec8>?

**Comment by heidi-ann** [comment]
how can i tell oasis to name the executable mldig.native instead of dig_unix.native

currently the oasis file says:
```
Executable mldig
  Path:               lwt
  MainIs:             dig_unix.ml
  Build$:             flag(tests) && flag(lwt)
  Custom:             true
  CompiledObject:     best
  Install:            false
  BuildDepends:       lwt, lwt.unix, lwt.syntax, dns, dns.lwt, re, re.str, ipaddr, cmdliner
```

**Comment by avsm** [comment]
The binary will always be built as its filename, but oasis will install it as `mldig`.  Why have you renamed it to `dig` though?  It should not be confused with the traditional `dig` command installed by BIND.

**Comment by avsm** [comment]
(The splitting of Mldig's functionality so that Mirage apps can use it is great)

**Comment by heidi-ann** [comment]
@dsheets asked me to rename the modules from mldig to dig

There's more work to done before theres a mirage dig but i just wanted the pretty printing functionality to debug mirage apps

**Comment by dsheets** [comment]
Sorry, I wasn't clear. I meant naming the module containing the `dig` functionality `Dig` but the executable front-ends named `mldig`.

**Comment by dsheets** [comment]
the module containing the *generic* `dig` functionality

**Comment by heidi-ann** [comment]
I think we are all in agreement. We want the modules called dig but the executable mldig to avoid a naming collision with normal dig

**Comment by avsm** [comment]
Has this been merged separately, @dsheets?

**Comment by dsheets** [comment]
Nope, I thought there was some issue with the executable name... but it looks OK to me right now?

**Pull request merged**
