### PR TITLE
Add build-test to opam so that unit tests run on Travis CI

### LINKED ISSUE #74: The unit tests no longer run on Travis CI
Prior to 27fbdb1e302266ffe245910bccc5d0b45bc54ac7 the unit tests ran as part of the Travis CI build, but as far as I can tell they don't any more. I believe this is because "--enable-tests" is not passed to setup.ml configure.

### PR DESCRIPTION
**Pull request by infidel**
Fixes #74

### CODE REVIEW

**Comment by infidel** [comment]
Build 172.1 and 172.5 failures are due to the unrelated error "Unbound module Nocrypto_entropy_lwt". Build 172.2 failure looks like a transient network problem. The other two builds are OK.

**Comment by samoht** [comment]
See https://github.com/ocaml/opam-repository/pull/4232 for the fix for `Nocrypto_entropy_lwt`. I'm restarting the other jobs.

**Comment by dsheets** [comment]
I've opened #2231 to track what looks like an opam/solver bug. Perhaps the root cause is actually something for which we're responsible but I am failing to detect it at this time.

**Comment by samoht** [comment]
The error:

```
#=== ERROR while installing mirage-flow.1.0.1 =================================#
# opam-version 1.2.2
# os           linux
# command      make
# path         /home/travis/.opam/system/build/mirage-flow.1.0.1
# compiler     system (4.01.0)
# exit-code    2
# env-file     /home/travis/.opam/system/build/mirage-flow.1.0.1/mirage-flow-20188-d4902a.env
# stdout-file  /home/travis/.opam/system/build/mirage-flow.1.0.1/mirage-flow-20188-d4902a.out
# stderr-file  /home/travis/.opam/system/build/mirage-flow.1.0.1/mirage-flow-20188-d4902a.err
### stdout ###
# [...]
# File "lib/lwt-io/lwt_io_flow.ml", line 57, characters 8-13:
# Warning 26: unused variable close.
# /home/travis/.opam/system/bin/ocamlfind ocamlopt -a lib/lwt-io/lwt_io_flow.cmx -o lib/lwt-io/lwt-io.cmxa
# /home/travis/.opam/system/bin/ocamlfind ocamlopt -shared lib/lwt-io/lwt-io.cmxa lib/lwt-io/lwt_io_flow.cmx -o lib/lwt-io/lwt-io.cmxs
# /home/travis/.opam/system/bin/ocamlfind ocamldep -package alcotest -package cstruct -package lwt -package lwt.unix -package mirage-types.lwt -modules lib_test/test.ml > lib_test/test.ml.depends
# /home/travis/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I lib -I lib/lwt-io -package alcotest -package cstruct -package lwt -package lwt.unix -package mirage-types.lwt -I lib_test -I lib -I lib/lwt-io -o lib_test/test.cmo lib_test/test.ml
# + /home/travis/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -I lib -I lib/lwt-io -package alcotest -package cstruct -package lwt -package lwt.unix -package mirage-types.lwt -I lib_test -I lib -I lib/lwt-io -o lib_test/test.cmo lib_test/test.ml
# File "lib_test/test.ml", line 37, characters 11-30:
# Error: Unbound module OUnit
# Command exited with code 2.
### stderr ###
# E: Failure("Command ''/usr/bin/ocamlbuild' lib/mirage-flow.cma lib/mirage-flow.cmxa lib/mirage-flow.a lib/mirage-flow.cmxs lib/lwt-io/lwt-io.cma lib/lwt-io/lwt-io.cmxa lib/lwt-io/lwt-io.a lib/lwt-io/lwt-io.cmxs lib_test/test.native -tag debug -tag tests' terminated with error code 10")
# make: *** [build] Error 1
```

should be fixed by https://github.com/mirage/mirage-flow/pull/7 if that's the case I'll cut a new release

**Comment by samoht** [comment]
And https://github.com/ocaml/opam-repository/pull/4340

**Comment by dsheets** [comment]
I don't see that error at all. I still see the `Nocrypto_entropy_lwt` errors. :cry: I think Travis has broken JavaScript magic shit.

**Comment by dsheets** [comment]
I've restarted the failed job now that all the opam updates are in. I can't see the actual error log as, despite all my cache clearing effort, I still get the `Nocrypto_entropy_lwt` error(s).

**Pull request merged**
