### PR TITLE
port to topkg

### PR DESCRIPTION
**Pull request by hannesm**
- `-safe-string` does _as well_ not work in here
- only the first four testsuites in `lib_test/ounit` are working here (not: `Test_dns_resolver_unix.tests`, `Test_dns_server_mirage.tests`, `Test_mdns_responder.tests`, `Test_mdns_resolver_mirage.tests`) -- this is no change to before (something with using lwt via oUnit) -- maybe someone else (or travis) has more luck!?
- async does not install here, thus the async sublibraries aren't tested at all

I cleaned up the dependencies in opam merlin _tags and META.  Please tell if you spot trouble 

Sublibraries: I renamed `dns.lwt` to `dns.lwt-unix` (this affects users, but having a `lwt-core` and an `lwt` sublibrary, where the `lwt` depended on `lwt-core` drove me mad).

I also updated the `mirage-dns` opam file to reflect the mirage depopts of dns.

if you can help with either `tests` or `async`, please tell so.  In addition, there is `lib_test/mirage` and `lib_test/mirage-mdns` which are unikernels and I don't know exactly what to do with them ;) (maybe build via `.travis.yml` and a shell script!?)

feedback welcome.

### CODE REVIEW

**Comment by hannesm** [comment]
CI failures: 4.02 doesn't work since tests need mirage-protocols, which is >=4.03

some testruns fail (I commented some out in 11684d7):
```
### stdout ###
# .........................EEEEEEEEEE....
### stderr ###
# [...]
# Called from file "src/oUnitRunnerProcesses.ml", line 213, characters 14-54
# Called from file "src/oUnitRunner.ml", line 358, characters 15-37
# Called from file "list.ml", line 88, characters 24-34
# Called from file "src/oUnitRunner.ml", line 462, characters 21-43
# Called from file "src/oUnitRunner.ml", line 499, characters 18-36
# Called from file "src/oUnitUtils.ml", line 172, characters 12-15
# Called from file "src/oUnitCore.ml", line 83, characters 4-59
# Called from file "src/oUnitCore.ml", line 172, characters 10-55
# Called from file "lib_test/ounit/test.ml", line 5, characters 2-255
# pkg.ml: [ERROR] Some tests failed.
```

on my local machine, I get test failures of the form:
```
..........................Fatal error: exception Unix.Unix_error(Unix.EINTR, "select", "")
Raised by primitive operation at file "src/oUnitRunnerProcesses.ml", line 191, characters 32-56
```

with varying system calls (`send`, `select`)... I also end up with leftover `test.native` using 100% CPU..

**Comment by hannesm** [comment]
new CI failure is in the async part:
```
# + ocamlfind ocamlc -c -g -bin-annot -principal -package 'async async_kernel threads' -package 're re.str ipaddr uri base64 hashcons cstruct result' -w A-3-4-9-26-27-29-32-33-34-37-39-40-41-42-44-45-48-60 -color always -I async -I lwt -I lib -I mirage -o async/async_dns_resolver.cmi async/async_dns_resolver.mli
# ocamlfind: Error from package `threads': Missing -thread or -vmthread switch
# Command exited with code 2.
```

if anyone has an idea/fix for this... is the `threads` package really needed for the async pieces (I copied it from _oasis)?

**Comment by avsm** [comment]
Hm, I'm always confused by the `threads` ocamlfind package _vs_ the tag -- @diml, which is needed to link to Async correctly?

**Comment by diml** [comment]
You need both, but if you use oasis adding threads as an explicit dependency should be enough. In the previous command line you need both `-package threads` and `-thread`.

Basically:
- `-package threads -thread` = system threads
- `-package threads -vmthread` = vm threads (nobody uses this)

**Comment by hannesm** [comment]
thanks, this went further (after adding `thread` to `_tags`).  I'd say ocaml-dns is working now (.1 fails on jitsu), and this PR can be merged (what needs to be done is fixing reverse dependencies using `dns.lwt` to use `dns.lwt-unix` instead).

```
#=== ERROR while installing jitsu.0.3.0 =======================================#
# opam-version         1.2.2 (58ef3b8213100953848d362f7120a30356d7f77d)
# os                   linux
# command              make
# path                 /home/opam/.opam/4.03.0/build/jitsu.0.3.0
# compiler             4.03.0
# exit-code            2
# env-file             /home/opam/.opam/4.03.0/build/jitsu.0.3.0/jitsu-14041-55c567.env
# stdout-file          /home/opam/.opam/4.03.0/build/jitsu.0.3.0/jitsu-14041-55c567.out
# stderr-file          /home/opam/.opam/4.03.0/build/jitsu.0.3.0/jitsu-14041-55c567.err
### stdout ###
# Version 0.3.0
# Detected backends: 
# mkdir -p /home/opam/.opam/4.03.0/build/jitsu.0.3.0/bin
# cd /home/opam/.opam/4.03.0/build/jitsu.0.3.0/src ; ocamlfind ocamlopt -w A-4-44  -package lwt.syntax,lwt,dns.lwt,cmdliner,ezxmlm,ipaddr,str,conduit,conduit.lwt-unix,irmin.unix,xenstore,xenstore_transport,xenstore_transport.lwt,uuidm -linkpkg -g  /home/opam/.opam/4.03.0/build/jitsu.0.3.0/src/jitsu_version.ml vm_stop_mode.ml vm_state.ml xenstore.ml backends.mli vm_backends.ml options.ml rumprun.ml  dns_helpers.ml irmin_backend.ml synjitsu.mli synjitsu.ml jitsu.mli jitsu.ml main.ml -o /home/opam/.opam/4.03.0/build/jitsu.0.3.0/bin/jitsu -syntax camlp4o
# Makefile:58: recipe for target '/home/opam/.opam/4.03.0/build/jitsu.0.3.0/bin/jitsu' failed
### stderr ###
# ocamlfind: Package `libvirt' not found
# ocamlfind: Package `xen-api-client' not found
# ocamlfind: Package `xenctrl' not found
# /bin/sh: 1: [: unexpected operator
# ocamlfind: Package `dns.lwt' not found
# make: *** [/home/opam/.opam/4.03.0/build/jitsu.0.3.0/bin/jitsu] Error 2
```

**Comment by hannesm** [comment]
@avsm willing to merge?  someone with access to a box where the tests (which are commented out as part of this PR) compile and run successfully (maybe @avsm?) may want to look whether they still run successfully after merging this PR (and if not, investigate and fix the upcoming issues)..

If it helps for merging, I can revert the ocamlfind lib (`dns.lwt` -> `dns.lwt-unix`) name change!?

**Comment by avsm** [comment]
thank you for this, @hannesm!

**Pull request merged**
