### PR TITLE
Updates (README, domain-name, ..)

### PR DESCRIPTION
**Pull request by hannesm**
this are cherry-picks from the udns repository. it is slightly confusing now to have both repositories with different git history, and some issues tracked in either of them :/ (I closed several issues in this repository)

### CODE REVIEW

**Comment by cfcs** [comment]
I say LGTM, but I'm a bit worried about the two repositories drifting apart, increasing the maintenance burden.

Perhaps the easiest solution would be to just archive the other mirror and move development here?

**Comment by hannesm** [comment]
@cfcs yes, good idea.

**Comment by hannesm** [comment]
could you approve, so that I'm able to merge this? ;) (in this repository, approval is required!)

**Comment by cfcs** [comment]
Sorry, yes, I hadn't noticed :)

**Comment by hannesm** [comment]
I archived the roburio/udns.git repository and opened various issues in this repository, some with milestone 2.0.0. if I missed something, please open new issues (and assign milestone 2.0.0 if we should have this before an initial public release). would be great to get an initial public release in july 2019!

**Pull request merged**
